### ISSUE TITLE
thoughts about necessary CSS adjustments

### ISSUE THREAD

**Issue by BurningTreeC** [TiddlyWiki/aTW#2]
TiddlyWiki on small devices needs some css adjustments for easier accessibility

I'd like to gather ideas/proposals in this issue

Finally I think we'll create a plugin that the app uses (for every wiki opened inside it?) containing those adjustments

1. sidebar positioning
2. edittemplate appearance, handling of tiddlers that are being edited
3. accessibility of pagecontrols
4. the sidebar-toggle button
5. buttons/tabs in general / size / positioning
6. tiddler frames (opinionated)
    - should have a bit of space left and right, maybe 0.5em
    - should have those rounded corners
    - could probably look like the google cards used in google now

**Comment by Jermolene** [comment]
A decent mobile view is definitely an issue for TW5, but I'd suggest not tackling it as part of the aTW work for the moment, mainly because it's not specific to aTW, and so we should address it in the main TW group.

There have been some good mobile themes for TW5 in the past. We might consider suggesting that one or other of them migrates to the core plugin library as a preliminary step.

**Comment by BurningTreeC** [comment]
@Jermolene , I'd like to use this issue to keep track of "problems" I discover, it's not a priority for the app itself
