### ISSUE TITLE
thoughts about layouts

### ISSUE THREAD

**Issue by BurningTreeC** [TiddlyWiki/aTW#5]
Android Studio offers a wide selection of layouts

A drawer navigation layout is a panel we can swipe in from the left, on the right the main content is displayed

A fab button is a small button in the bottom right corner that reveals another panel at the bottom

And there are more, Android users know them, they're widely used in other apps and pretty standard

What I have in mind is a landing page like the one TiddlyDesktop has

That page is a webview based on a HTML file that ships with the application

From that page new wikies can be opened. I think new wikies shouldn't load in the same webview but always create a new app instance, so that we can jump from one to the other using the system ui, closing one without affecting the other...

First thoughts

**Comment by TiddlyTweeter** [comment]
In some ways I think coinciding aTW with TD in some aspects is a very good idea. Beyond Android use its also interesting to echo TD which is actually a very good pitch IMO.

**Comment by BurningTreeC** [comment]
Hi @TiddlyTweeter , I'd like to reuse things that have already been created where it's possible

using the TD approach is convenient, because it already ships the concept of how to manage the wikies, and this can be kept in sync with new things that happen in TD

the layout questions here are also about if we need (and/or want) those additional android drawers and buttons at all

I think it would be a good approach to leave as much handling, layouting and managing as possible to tiddlywiki itself, what do others think?

**Comment by Wattaged** [comment]
I think the layout needs to be preceeded by a definition of aTW's proposed scope and function because one influences the other. Is aTW going to be;

1. A finished, fixed product like most others in the playstore, well designed for mobile, which is 'download and use',  requiring minimal user involvement to make it do what it does? I'm imagining an aTW core, with a very simple ui  that does something pretty simple to start with (eg OmniNotes - my goto example of effective app simplicity). Plugins might then be downloadable 'extras' which enhance, extend or change that basic functionality. (eg from notetaker to flashcarder, to contact manager, to photo gallery, to GTD. As we know TW can do almost anything). In a sense this would set the app up almost as an OS with its own ecosystem, within Android. (Thinking big!)

2. A full TW, with all the flexibility and user intervention that requires, but simply in a mobile friendly design? I'm a tinkerer so I love that flexibility and trawling the GG forum looking for ways to botch things for myself, but imagine the maintenance and support implications when the user base expands to the playstore or the millions of Android users.

3. Option 1 but with option 2 available under the hood for those who know how. Maybe still some support problems, but it's at the users own risk, they were warned.

4. Your options here.

5. Maybe the app will never make it to the playstore and isn't intended to but that again influences the design options. I think a project like this could be big for TW. It needs a bit of a manifesto first, with some goals, aims and objectives, project management style language. We need a gantt chart plugin!

**Comment by BurningTreeC** [comment]
the problem with the layout is - I have a hard time trying to manage multiple tasks
so I'll make the app single-task for now, which means that there will be only one open task in the "recents" screen and opening a new wiki will replace the opened one. there will be a prompt that asks for saving when leaving a wiki

**Comment by Wattaged** [comment]
Speaking for myself, I don't really need any additional UI elements from the app. The version I'm using now operates like a dedicated browser with a saver mechanism built in. Those are the most important to me. A single wiki app is ok for me and less confusing for brand new users from the playstore I'd imagine. The wiki itself provides the UI, not the app.

Human readable timestamps on backup files would be good.

Memory usage seems high.

If unique wiki names saved to their own unique directories that would be good. 

Tabbed view possible?
The app already opens a different wiki for me if I include a link to it in my 'master' index.html wiki. But if I then save a change in that 'opened from link' wiki it becomes the index.html in Documents, overwriting the original 'master' index.html.
When I open a wiki in a normal mobile browser it doesn't offer an 'open file' menu or wiki selection menu. I have to paste the file address into the url bar, or put a link in a tiddler and open it in a new tab. If each wiki opened in a new tab but saved to its own directory might that work?

**Comment by BurningTreeC** [comment]
@Wattaged, you're using one of the old versions I guess

the wiki locations and where they're saved are handled totally different now

**Comment by BurningTreeC** [comment]
@Wattaged, you're using one of the old versions I guess

the wiki locations and where they're saved are handled totally different now

**Comment by Wattaged** [comment]
Yes, only the 2nd version. Links to an apks eemed to disappear after that. Anywhere I can get the most recent? I don't have android studio.

**Comment by BurningTreeC** [comment]
Here's a link with some testing impressions of the current state

https://youtu.be/pvmD3phH8Yg
